# Generated by Django 5.2.16 on 2026-09-15 14:20

import django.contrib.postgres.fields
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='communication_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sponsor_events', 'Sponsor events & job opportunities'), ('partner_announcements', 'Community partner announcements and opportunities'), ('conference_cfps', 'Conferences/CFPs in your area'), ('volunteer_opportunities', 'BPD community volunteer opportunities')], max_length=40), blank=True, default=list, help_text="What you'd like to hear about.", size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Where you currently reside. Used to match you to a region.', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='member_type',
            field=models.CharField(blank=True, choices=[('member', 'BPD Member'), ('supporter', 'Friend / Supporter / Ally')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='subcommunities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('latam', 'LATAM'), ('indigenous', 'Native/Indigenous (including Maori, Aboriginal)'), ('pacific_islander', 'Pacific Islander'), ('asian_religious_minority', 'Asian Religious Minority')], max_length=40), blank=True, default=list, help_text='Subcommunities you identify with, so we can share opportunities relevant to you.', size=None),
        ),
    ]
