# Generated by Django 5.2.16 on 2026-09-15 16:13

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_communication_preferences_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The address this invite is for. The link only works for this email.', max_length=254)),
                ('token', models.CharField(default=users.models._invite_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=users.models._invite_expiry)),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invite', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='Groups applied to the account automatically when the invite is accepted.', to='auth.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
