# Generated by Django 5.2.16 on 2026-09-22 14:39

import django.contrib.postgres.fields
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_linkedin_user_mastodon_user_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_communication_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sponsor_events', 'Sponsor events & job opportunities'), ('partner_announcements', 'Community partner announcements and opportunities'), ('conference_cfps', 'Conferences/CFPs in your area'), ('volunteer_opportunities', 'BPD community volunteer opportunities')], max_length=40), blank=True, default=users.models._all_communication_preferences, help_text="What you'd like as app notifications.", size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='communication_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sponsor_events', 'Sponsor events & job opportunities'), ('partner_announcements', 'Community partner announcements and opportunities'), ('conference_cfps', 'Conferences/CFPs in your area'), ('volunteer_opportunities', 'BPD community volunteer opportunities')], max_length=40), blank=True, default=list, help_text="What you'd like emailed to you.", size=None),
        ),
    ]
