# Generated by Django 5.2.16 on 2026-09-23 20:34

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_app_communication_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='How many times this link can be used. Leave blank for unlimited uses (the expiration date is then the only limit).', null=True),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='use_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='accepted_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='Most recent account this link was used for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='email',
            field=models.EmailField(blank=True, help_text='Leave blank for a general-purpose signup link anyone can use. Set an address to invite one specific person — the link will only work for that email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=users.models._invite_expiry, help_text='When this link stops working. Leave blank for no date limit (the uses limit is then the only limit).', null=True),
        ),
    ]
