# Generated by Django 5.2.16 on 2026-09-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_invitelink_max_uses_invitelink_use_count_and_more'),
        ('users', '0006_user_website'),
    ]

    operations = [
    ]
