# Generated by Django 5.2.16 on 2026-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_invite_and_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state_province',
            field=models.CharField(blank=True, help_text='Your state, province, or other local region — helps us connect you to opportunities (like volunteering) closer to you. For a US state, this can also narrow your region below the country level.', max_length=100),
        ),
    ]
