# Generated by Django 5.2.16 on 2026-07-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventindexpage_body_alter_eventpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsoredevent',
            options={'ordering': ['sort_order'], 'verbose_name': 'sponsored event'},
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional, for internal records. Never shown on the public site.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes. Not shown publicly.'),
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='paid',
            field=models.BooleanField(default=True, help_text='Tick when Black Python Devs transferred funds. Leave unticked for community sponsorships contributed as visibility, volunteer time, or other non-monetary support.'),
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', help_text='Only completed sponsorships appear on the public events page.', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsoredevent',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
