# Generated by Django 5.2.16 on 2026-07-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_sponsoredevent_options_sponsoredevent_amount_and_more'),
        # Copy the rows into the sponsorships app before dropping this table.
        ('sponsorships', '0002_migrate_sponsored_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsoredEvent',
        ),
    ]
