# Generated by Django 5.2.16 on 2026-07-28 22:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_sponsoredevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4), ('iframe', 8), ('callout', 10), ('card_grid', 17), ('ambassador_apply', 21), ('html', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'core/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessible title for the iframe.'}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('56.25', '16:9'), ('75', '4:3'), ('100', '1:1')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('src', 6), ('aspect_ratio', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 1)]], {}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 11), ('text', 12), ('link_url', 9), ('link_text', 9)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link shown below the grid.', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('heading', 9), ('cards', 14), ('link_url', 15), ('link_text', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Apply', 'required': False}), 19: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional copy shown above the button.', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Apply Now'}), 21: ('wagtail.blocks.StructBlock', [[('heading', 18), ('text', 19), ('button_text', 20)]], {}), 22: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Raw HTML — available to editors with the required permission only.'})}),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4), ('iframe', 8), ('callout', 10), ('card_grid', 17), ('ambassador_apply', 21), ('html', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'core/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessible title for the iframe.'}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('56.25', '16:9'), ('75', '4:3'), ('100', '1:1')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('src', 6), ('aspect_ratio', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 1)]], {}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 11), ('text', 12), ('link_url', 9), ('link_text', 9)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link shown below the grid.', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('heading', 9), ('cards', 14), ('link_url', 15), ('link_text', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Apply', 'required': False}), 19: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional copy shown above the button.', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Apply Now'}), 21: ('wagtail.blocks.StructBlock', [[('heading', 18), ('text', 19), ('button_text', 20)]], {}), 22: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Raw HTML — available to editors with the required permission only.'})}),
        ),
    ]
