# Generated by Django 5.2.16 on 2026-08-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventindexpage_body_alter_eventpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipSummitPage',
            fields=[
                ('eventpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.eventpage')),
                ('city', models.CharField(blank=True, help_text='City and region, e.g. "Austin, TX". Used in the summary line.', max_length=120)),
                ('host_event_name', models.CharField(blank=True, help_text='The conference this summit runs alongside, e.g. "PyTexas". Leave blank if standalone.', max_length=160)),
                ('host_event_url', models.URLField(blank=True)),
                ('host_event_start', models.DateField(blank=True, help_text='First day of the host conference.', null=True)),
                ('host_event_end', models.DateField(blank=True, help_text='Last day of the host conference.', null=True)),
                ('registration_url', models.URLField(blank=True, help_text='Leave blank until registration opens — the page then says announcements are coming.')),
                ('cfp_url', models.URLField(blank=True, help_text='Leave blank until the call for speakers opens.', verbose_name='Call for speakers URL')),
                ('who_is_invited', models.TextField(blank=True, help_text='Leave blank to use the standard wording: “Anyone in leadership or wanting to get into leadership at the local, regional, or global level of the Python community.”')),
                ('code_of_conduct_url', models.CharField(blank=True, default='/code-of-conduct/', help_text='The Black Python Devs Code of Conduct.', max_length=255)),
                ('host_code_of_conduct_url', models.URLField(blank=True, help_text="The host conference's Code of Conduct, if there is one.")),
            ],
            options={
                'verbose_name': 'leadership summit',
            },
            bases=('events.eventpage',),
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='tito_event',
        ),
    ]
