# Generated by Django 5.2.16 on 2026-08-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_leadershipsummitpage_remove_eventpage_tito_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='commitchange_campaign_id',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='commitchange_designation',
        ),
    ]
