# Generated by Django 5.2.16 on 2026-08-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventindexpage_body_alter_eventpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipsummitpage',
            name='afternoon_video_url',
            field=models.URLField(blank=True, help_text="YouTube link to the afternoon session. Leave blank until it's published.", verbose_name='Afternoon session recording'),
        ),
        migrations.AddField(
            model_name='leadershipsummitpage',
            name='morning_video_url',
            field=models.URLField(blank=True, help_text="YouTube link to the morning session. Leave blank until it's published.", verbose_name='Morning session recording'),
        ),
    ]
