# Generated by Django 5.2.16 on 2026-08-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_leadershipsummitpage_afternoon_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadershipsummitpage',
            name='who_is_invited',
        ),
    ]
