# Generated by Django 5.2.16 on 2026-08-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_leadershipsummitpage_who_is_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipsummitpage',
            name='cfp_deadline',
            field=models.DateField(blank=True, help_text='After this date the call is shown as closed rather than open.', null=True, verbose_name='Call for speakers closes'),
        ),
    ]
