# Generated by Django 5.2.16 on 2026-08-11 22:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_speaker'),
        ('events', '0011_leadershipsummitpage_cfp_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('track', models.CharField(blank=True, help_text='Optional heading when a day splits, e.g. "Morning". Rows sharing one are shown together.', max_length=80)),
                ('time', models.CharField(help_text='e.g. "09:00" or "8:00am - 9:00am"', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('presenter', models.CharField(blank=True, help_text='Used when the presenter has no speaker record — a sponsor, "Everyone", and so on. Ignored if a speaker is chosen above.', max_length=160)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='events.leadershipsummitpage')),
                ('speaker', models.ForeignKey(blank=True, help_text='Pick from the speaker snippets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.speaker')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummitSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('group', models.CharField(blank=True, default='Speakers', help_text='Section heading these appear under, e.g. "Keynote Speakers". Speakers sharing a heading are shown together, so keep them next to each other.', max_length=80)),
                ('talk_title', models.CharField(blank=True, help_text='The talk they gave at this summit.', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_lineup', to='events.leadershipsummitpage')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summit_appearances', to='core.speaker')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
