# Generated by Django 5.2.16 on 2026-09-15 21:27

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_online', models.BooleanField(default=False, help_text="Online-only communities aren't tied to one region. Their messages to leadership reach every region instead of just one.")),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Where this community is based. Leave blank for an online-only community.', max_length=2)),
                ('region', models.CharField(blank=True, editable=False, max_length=80)),
                ('notes', models.TextField(blank=True, help_text='Internal notes. Not shown to community admins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_links', to='communities.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_admin_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['community__name'],
            },
        ),
        migrations.AddField(
            model_name='community',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_communities', through='communities.CommunityAdmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='communityadmin',
            constraint=models.UniqueConstraint(fields=('community', 'user'), name='unique_community_admin'),
        ),
    ]
