# Generated by Django 5.2.16 on 2026-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='state_province',
            field=models.CharField(blank=True, help_text="This community's state or province, if relevant. For a US state, this can also narrow its region below the country level, same as User.state_province.", max_length=100),
        ),
    ]
