# Generated by Django 5.2.16 on 2026-07-23 14:44

import modelsearch.index
import wagtail.fields
import wagtail.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('bpd_role', models.CharField(blank=True, max_length=160)),
                ('website', models.URLField(blank=True)),
                ('mastodon', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='description')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=40)),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.images.models.ImageFileMixin, modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CustomRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_spec', models.CharField(db_index=True, max_length=255)),
                ('file', wagtail.images.models.WagtailImageField(height_field='height', storage=wagtail.images.models.get_rendition_storage, upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('focal_point_key', models.CharField(blank=True, default='', editable=False, max_length=16)),
            ],
            bases=(wagtail.images.models.ImageFileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(blank=True, default='Black Python Devs is a US Non-Profit Organization under the fiscal hosting of the GNOME Foundation. The foundation aims to expand access to Python communities and resources to communities of Black Python Developers around the world.')),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FoundationalSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('year', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('role', models.CharField(choices=[('executor', 'Executor'), ('lead', 'Team Lead'), ('advisor', 'Advisor'), ('council', 'Leadership Council')], default='council', max_length=20)),
                ('photo_url', models.CharField(blank=True, help_text='External or /static/ photo URL, used when no image is uploaded.', max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=60)),
                ('url', models.CharField(help_text='Relative path (/about/) or full URL.', max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Iconoir class name, e.g. iconoir-journal-page', max_length=60)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True)),
                ('promo_code', models.CharField(blank=True, max_length=60)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('logo_static_path', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_url', models.URLField(blank=True, default='https://discord.gg/XUc3tFqCT3')),
                ('linkedin_url', models.URLField(blank=True, default='https://www.linkedin.com/company/black-python-devs')),
                ('linkedin_group_url', models.URLField(blank=True, default='https://www.linkedin.com/groups/14336241/')),
                ('x_url', models.URLField(blank=True, default='https://x.com/blackpythondevs')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/blackpythondevs/')),
                ('github_url', models.URLField(blank=True, default='https://github.com/BlackPythonDevs')),
                ('contact_email', models.EmailField(blank=True, default='contact@blackpythondevs.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Social links',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('logo_static_path', models.CharField(blank=True, help_text='Fallback path under /static/ if no image has been uploaded, e.g. images/jetbrains.webp', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ToastSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='Black Python Devs', max_length=100)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Announcement toast',
            },
        ),
    ]
