# Generated by Django 5.2.16 on 2026-08-11 22:46

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foundational_support_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(blank=True, help_text='Their site, LinkedIn, or Mastodon.')),
                ('photo_url', models.CharField(blank=True, help_text='External or /static/ photo URL, used when no image is uploaded.', max_length=500)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
