# Generated by Django 5.2.16 on 2026-09-15 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_speaker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='affiliations',
            field=models.CharField(blank=True, help_text="Other organizations or communities you're affiliated with.", max_length=255),
        ),
        migrations.AddField(
            model_name='leader',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this roster entry to a site account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
