# Generated by Django 5.2.16 on 2026-09-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leader_affiliations_leader_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customimage',
            options={'permissions': [('choose_customimage', 'Can choose image')]},
        ),
    ]
