# Generated by Django 5.2.16 on 2026-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_onboarding_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contract value, for internal records. Never shown on the public site.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='expires_at',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='invoice_paid_date',
            field=models.DateField(blank=True, help_text='When Black Python Devs received payment. The sponsorship term runs one year from this date.', null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring soon'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tier',
            field=models.CharField(blank=True, choices=[('community', 'Community'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20),
        ),
    ]
