# Generated by Django 5.2.16 on 2026-09-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_executor_group_sponsor_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='tier',
        ),
    ]
