# Generated by Django 5.2.16 on 2026-08-11 18:13

import django.db.models.deletion
import nominations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(help_text="The nominee's full name.", max_length=200)),
                ('nominee_email', models.EmailField(help_text='Best contact email for the nominee.', max_length=254)),
                ('nominee_url', models.URLField(blank=True, help_text='Optional link — GitHub, LinkedIn, or a personal site.')),
                ('statement', models.TextField(help_text='Why this person should serve on the Leadership Council.')),
                ('contributions', models.TextField(blank=True, help_text="Optional. What they've already contributed to Black Python Devs or the wider community.")),
                ('nominee_consulted', models.BooleanField(default=False, help_text="Tick if you've confirmed the nominee is willing to serve.")),
                ('term_year', models.PositiveIntegerField(db_index=True, default=nominations.models.current_term_year, help_text='The nomination cycle this belongs to.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes. Not shown to the nominee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominator', models.ForeignKey(help_text='The leader who put this person forward.', on_delete=django.db.models.deletion.CASCADE, related_name='council_nominations', to=settings.AUTH_USER_MODEL)),
                ('nominee_user', models.ForeignKey(blank=True, help_text='Link the nomination to a site account, if the nominee already has one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_nominations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'council nomination',
                'verbose_name_plural': 'council nominations',
                'ordering': ['-term_year', 'nominee_name'],
                'constraints': [models.UniqueConstraint(fields=('nominator', 'nominee_email', 'term_year'), name='unique_nomination_per_nominator_and_cycle')],
            },
        ),
    ]
