# Generated by Django 5.2.16 on 2026-09-27 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpage_body'),
        ('nominations', '0001_initial'),
        ('users', '0007_merge_invite_and_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='councilnomination',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='councilnomination',
            name='announcement_page',
            field=models.ForeignKey(blank=True, help_text='Draft announcement created once onboarding (profile + photo) is complete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.blogpage'),
        ),
        migrations.AddField(
            model_name='councilnomination',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='councilnomination',
            name='invite_link',
            field=models.ForeignKey(blank=True, help_text='The invite emailed to the nominee to accept their council seat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_nomination', to='users.invitelink'),
        ),
        migrations.AddField(
            model_name='councilnomination',
            name='objection_window_closes_at',
            field=models.DateTimeField(blank=True, help_text='Set to 24 hours after seconding. Objections can be raised until this passes.', null=True),
        ),
        migrations.AddField(
            model_name='councilnomination',
            name='onboarding_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='councilnomination',
            name='seconded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='councilnomination',
            name='seconded_by',
            field=models.ForeignKey(blank=True, help_text='The other Council-tier leader who seconded this nomination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_nominations_seconded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='councilnomination',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under review'), ('seconded', 'Seconded — objection window open'), ('confirmation_sent', 'Confirmation sent to nominee'), ('accepted_pending_onboarding', 'Accepted — completing onboarding'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='NominationObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='nominations.councilnomination')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_nomination_objections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
