# Generated by Django 5.2.16 on 2026-09-23 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('intro', models.TextField(blank=True, help_text='Optional blurb shown at the top of the election page.')),
                ('nomination_opens_at', models.DateTimeField()),
                ('nomination_closes_at', models.DateTimeField()),
                ('voting_opens_at', models.DateTimeField()),
                ('voting_closes_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'election',
                'verbose_name_plural': 'elections',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text="Why you're running for the council.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='elections.election')),
            ],
            options={
                'verbose_name': 'candidacy',
                'verbose_name_plural': 'candidacies',
                'ordering': ['user__display_name'],
                'constraints': [models.UniqueConstraint(fields=('election', 'user'), name='one_candidacy_per_member_per_election')],
            },
        ),
    ]
