# Generated by Django 5.2.16 on 2026-09-23 18:37

import elections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='year',
            field=models.PositiveIntegerField(default=elections.models.default_election_year, unique=True),
        ),
        migrations.AlterModelTable(
            name='election',
            table='executor_elections',
        ),
    ]
