# Generated by Django 5.2.16 on 2026-09-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_year_alter_election_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='intro',
            field=models.TextField(blank=True, help_text='Optional blurb shown at the top of the election page. Markdown.'),
        ),
    ]
