# Generated by Django 5.2.16 on 2026-09-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_election_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='statement',
            field=models.TextField(help_text="Why you're running to be Executor."),
        ),
    ]
