# Generated by Django 5.2.16 on 2026-09-28 12:58

import django.db.models.deletion
import elections.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_alter_candidacy_statement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=elections.models._ballot_token, editable=False, max_length=64, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.election')),
            ],
            options={
                'verbose_name': 'ballot',
                'verbose_name_plural': 'ballots',
            },
        ),
        migrations.CreateModel(
            name='BallotRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='elections.ballot')),
                ('candidacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='elections.candidacy')),
            ],
            options={
                'verbose_name': 'ballot ranking',
                'verbose_name_plural': 'ballot rankings',
                'ordering': ['ballot_id', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('ballot', 'candidacy'), name='one_ranking_per_candidate_per_ballot'), models.UniqueConstraint(fields=('ballot', 'rank'), name='one_candidate_per_rank_per_ballot')],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote record',
                'verbose_name_plural': 'vote records',
                'constraints': [models.UniqueConstraint(fields=('election', 'user'), name='one_vote_per_member_per_election')],
            },
        ),
    ]
