# Generated by Django 5.2.16 on 2026-09-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_ballot_ballotranking_voterecord'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ballotranking',
            name='one_candidate_per_rank_per_ballot',
        ),
    ]
