# Generated by Django 5.2.16 on 2026-07-23 14:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True)),
                ('posts_per_page', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='post date')),
                ('description', models.TextField(blank=True, help_text='Shown in listings and as the meta description.')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4), ('iframe', 8), ('callout', 10), ('card_grid', 15), ('html', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'core/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessible title for the iframe.'}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('56.25', '16:9'), ('75', '4:3'), ('100', '1:1')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('src', 6), ('aspect_ratio', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 1)]], {}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 11), ('text', 12), ('link_url', 9), ('link_text', 9)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('heading', 9), ('cards', 14)]], {}), 16: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Raw HTML — available to editors with the required permission only.'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
