# Generated by Django 5.2.16 on 2026-09-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpage_body'),
        ('core', '0010_sponsor_contract_amount_sponsor_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlogPage',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogpage')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_posts', to='core.sponsor')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpage',),
        ),
    ]
