# Generated by Django 5.2.16 on 2026-10-01 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpage_body'),
        ('core', '0014_remove_sponsor_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Shown uncropped, letterboxed in a 3:2 frame in listings. Use a 3:2 image (e.g. 1200x800) to fill the frame. Transparent PNGs appear on a light background, so avoid white artwork.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage'),
        ),
    ]
