# Generated by Django 5.2.16 on 2026-07-28 22:09

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAmbassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The applicant's full name.", max_length=200)),
                ('email', models.EmailField(help_text='Best contact email for the applicant.', max_length=254)),
                ('school', models.CharField(help_text='School, college, or university.', max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Where the applicant is based.', max_length=2)),
                ('field_of_study', models.CharField(blank=True, max_length=200)),
                ('graduation_year', models.PositiveIntegerField(blank=True, help_text='Expected year of graduation.', null=True)),
                ('motivation', models.TextField(help_text='Why the applicant wants to be a Black Python Devs student ambassador.')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('waitlisted', 'Waitlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='applied', help_text='Accepted applicants are added to the Ambassadors group.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes. Not shown to the applicant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student ambassador',
                'verbose_name_plural': 'student ambassadors',
                'ordering': ['-created_at'],
            },
        ),
    ]
