# Generated by Django 5.2.16 on 2026-07-23 15:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('home', '0002_alter_aboutpage_body_alter_homepage_body_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', models.TextField(blank=True, default='Black Python Devs is a global community of Black Pythonistas. Membership is free — join us and connect with developers around the world.')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4), ('iframe', 8), ('callout', 10), ('card_grid', 17), ('html', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'template': 'core/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessible title for the iframe.'}), 6: ('wagtail.blocks.URLBlock', (), {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('56.25', '16:9'), ('75', '4:3'), ('100', '1:1')]}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('src', 6), ('aspect_ratio', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('heading', 9), ('text', 1)]], {}), 11: ('wagtail.blocks.CharBlock', (), {}), 12: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading', 11), ('text', 12), ('link_url', 9), ('link_text', 9)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional link shown below the grid.', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('heading', 9), ('cards', 14), ('link_url', 15), ('link_text', 16)]], {}), 18: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Raw HTML — available to editors with the required permission only.'})})),
                ('benefits_heading', models.CharField(blank=True, default='What you get', max_length=120)),
                ('form_heading', models.CharField(blank=True, default='Become a member', max_length=120)),
                ('form_help_text', models.CharField(blank=True, default="Enter your email and we'll send you a sign-in code. No password needed.", max_length=255)),
                ('discord_heading', models.CharField(blank=True, default='Connect your Discord account', max_length=120)),
                ('discord_body', wagtail.fields.RichTextField(blank=True, help_text='Explain what connecting Discord does — it grants the role that allows posting.')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
