# Generated by Django 5.2.16 on 2026-07-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('region', models.CharField(help_text='e.g. Africa, North America, South America', max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', help_text='Only completed sponsorships appear on the public events page.', max_length=20)),
                ('paid', models.BooleanField(default=True, help_text='Tick when Black Python Devs transferred funds. Leave unticked for community sponsorships contributed as visibility, volunteer time, or other non-monetary support.')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional, for internal records. Never shown on the public site.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes. Not shown publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sponsorship request',
                'verbose_name_plural': 'sponsorship requests',
                'ordering': ['-year', 'region', 'name'],
            },
        ),
    ]
