# Generated by Django 5.2.16 on 2026-07-26 13:19

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0003_executor_group'),
    ]

    operations = [
        # Preserve existing values: this is a rename, not a drop-and-recreate.
        migrations.RenameField(
            model_name='sponsorshiprequest',
            old_name='amount',
            new_name='amount_requested',
        ),
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='amount_requested',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the event asked for, for internal records. Never shown on the public site.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsorshiprequest',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text="Event country. The public listing groups by the country's region.", max_length=2),
        ),
        migrations.AddField(
            model_name='sponsorshiprequest',
            name='prospectus_url',
            field=models.URLField(blank=True, help_text="Link to the event's sponsorship prospectus."),
        ),
        migrations.AddField(
            model_name='sponsorshiprequest',
            name='start_date',
            field=models.DateField(help_text='Event start date. The year shown on the public site is taken from this.', null=True),
        ),
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='region',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='url',
            field=models.URLField(blank=True, help_text="The event's website."),
        ),
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='year',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
