# Generated by Django 5.2.16 on 2026-07-26 14:23

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0004_remove_sponsorshiprequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshiprequest',
            name='country',
            field=django_countries.fields.CountryField(help_text="Event country. The public listing groups by the country's region.", max_length=2),
        ),
    ]
