# Generated by Django 5.2.16 on 2026-09-15 14:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, help_text='Limit to members in these regions. Leave empty for every region.', size=None)),
                ('affinities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('latam', 'LATAM'), ('indigenous', 'Native/Indigenous (including Maori, Aboriginal)'), ('pacific_islander', 'Pacific Islander'), ('asian_religious_minority', 'Asian Religious Minority')], max_length=40), blank=True, default=list, help_text='Limit to members who identify with these subcommunities.', size=None)),
                ('recipient_count', models.PositiveIntegerField(default=0, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roles', models.ManyToManyField(blank=True, help_text='Limit to members of these groups. Leave empty to skip this filter.', related_name='+', to='auth.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
