# Generated by Django 5.2.16 on 2026-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_sponsor_and_partner_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(help_text="Markdown. Images become ![](url) — attach one below and it's added for you."),
        ),
    ]
