# Generated by Django 5.2.16 on 2026-09-24 23:30

import django.db.models.deletion
import service_award.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAwardNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(help_text="The nominee's full name.", max_length=200)),
                ('nominee_email', models.EmailField(help_text='Best contact email for the nominee.', max_length=254)),
                ('nominee_url', models.URLField(blank=True, help_text='Optional link — GitHub, LinkedIn, or a personal site.')),
                ('statement', models.TextField(help_text='Why this person deserves the Community Service Award.')),
                ('contributions', models.TextField(blank=True, help_text="Optional. What they've already contributed to Black Python Devs or the wider community.")),
                ('award_year', models.PositiveIntegerField(db_index=True, default=service_award.models.current_award_year, help_text='The award cycle this belongs to.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes. Not shown to the nominee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominator', models.ForeignKey(help_text='The leader who put this person forward.', on_delete=django.db.models.deletion.CASCADE, related_name='service_award_nominations', to=settings.AUTH_USER_MODEL)),
                ('nominee_user', models.ForeignKey(blank=True, help_text='Link the nomination to a site account, if the nominee already has one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_award_nominations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service award nomination',
                'verbose_name_plural': 'service award nominations',
                'ordering': ['-award_year', 'nominee_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAwardRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(blank=True, help_text='Used to exclude them from future nominations.', max_length=254)),
                ('award_year', models.PositiveIntegerField(default=service_award.models.current_award_year, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes, e.g. how the payment was made.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(blank=True, help_text='The nomination that led to this win, if there was one on file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award', to='service_award.serviceawardnomination')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_award_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'service award recipient',
                'verbose_name_plural': 'service award recipients',
                'ordering': ['-award_year'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceawardnomination',
            constraint=models.UniqueConstraint(fields=('nominator', 'nominee_email', 'award_year'), name='unique_service_award_nomination_per_nominator_and_cycle'),
        ),
    ]
